"""empty message

Revision ID: 83742081fe1d
Revises: 027fe28ddefa
Create Date: 2020-09-11 11:31:26.898441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83742081fe1d'
down_revision = '027fe28ddefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
